# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lista.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormLista(object):
    def setupUi(self, FormLista):
        FormLista.setObjectName("FormLista")
        FormLista.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FormLista)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(FormLista)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.PBzamknij = QtWidgets.QPushButton(FormLista)
        self.PBzamknij.setObjectName("PBzamknij")
        self.verticalLayout.addWidget(self.PBzamknij)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FormLista)
        QtCore.QMetaObject.connectSlotsByName(FormLista)

    def retranslateUi(self, FormLista):
        _translate = QtCore.QCoreApplication.translate
        FormLista.setWindowTitle(_translate("FormLista", "Lista adresów"))
        self.PBzamknij.setText(_translate("FormLista", "close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormLista = QtWidgets.QWidget()
    ui = Ui_FormLista()
    ui.setupUi(FormLista)
    FormLista.show()
    sys.exit(app.exec_())
